### ISSUE TITLE
Wrong order when importing tests to Runscope

### ISSUE THREAD

**Issue by tettomagic** [Runscope/paw-runscope#2]
When I import my tests from PAW to Runscope account, I got them in wrong order.

**Comment by mittsh** [comment]
This an issue related to the JavaScript API that Paw is exposing. We will be pushing a bugfix version this week, this extension will benefit directly from the fix, and all tests will be in the right order.

To give a little more context, the `requests` array passed here https://github.com/Runscope/paw-runscope/blob/master/TestGenerator.js#L5 wasn't ordered, we have fixed it on our dev branch already.

**Comment by mittsh** [comment]
We've fixed this bug and released Paw 3.0.8 today: https://paw.cloud/updates/3.0.8
You can update from Paw menu > Check for updates… it should fix this bug in the Runscope generator as well.

**Comment by tettomagic** [comment]
Great (y)
